
spring:
  datasource:
    url: jdbc:h2:mem:spookifydb
  h2:
    console:
      enabled: true
      path: /h2-console  
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true
    show-sql: true
  
  sql:
    init:
      platform: h2